name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'major|minor|patch'
        required: true
#      versionCode:
#        description: 'Version number (1.1.0)'
#        required: false

jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get current tag version
      id: get_tag
      run: |
        git describe --tags $(git rev-list --tags --max-count=1)
        echo ::set-output name=current_version::$(git describe --tags $(git rev-list --tags --max-count=1))
    - name: Bump release version
      id: next_version
      run: |
        # Build array from version string.
        a= ( ${${{steps.get_tag.outputs.current_version }}//./ } )
        if [[ "${{ github.event.inputs.semver }}" == "major" ]]; then ((a[0]++))
                                                                        a[1]=0
                                                                        a[2]=0
        fi
        if [[ "${{ github.event.inputs.semver }}" == "minor" ]]; then  ((a[1]++))
                                                                         a[2]=0
        fi
        if [[ "${{ github.event.inputs.semver }}" == "patch" ]]; then ((a[2]++))
        fi

        echo ::set-output name=next_version::$(${a[0]}.${a[1]}.${a[2]})
#      uses: zwaldowski/semver-release-action@v1
#      with:
#        dry_run: true
#        bump: ${{ github.event.inputs.semver }}
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#      uses: HardNorth/github-version-generate@v1.1.1

    - name: Test
      run: |
        echo current version ${{steps.get_tag.outputs.current_version }}
        echo next version "${{ steps.next_version.outputs.next_version }}"
    - name: Create release branch
      run: git checkout -b release/${{steps.get_tag.outputs.current_version }} #${{ github.event.inputs.versionCode }}
    - name: Initialize mandatory git config
      run: |
       git config user.name "GitHub Actions"
       git config user.email noreply@github.com
#    - name: Change version number
#      run: printf 'ext.version_code = ${{ github.event.inputs.versionCode }}' > app_versions.gradle
    - name: Update Changelog
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        version: ${{ github.event.inputs.versionCode }}
    - name: Commit changelog and manifest files
      id: make-commit
      run: |
        git add CHANGELOG.md
        git commit --message "Prepare release ${{ github.event.inputs.versionCode }}"
        echo "::set-output name=commit::$(git rev-parse HEAD)"
    - name: Push new branch
      run: git push origin release/${{ github.event.inputs.versionCode }}
    - name: Create pull request into master
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       head: release/${{ github.event.inputs.versionCode }}
       base: master
       title: ${{ github.event.inputs.versionCode }} into master
       reviewers: ${{ github.event.issue.user.login }}
       body: |
           Hi!
           This PR was created in response workflow running.
           I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.
    - name: Create pull request to develop
      uses: thomaseizinger/create-pull-request@1.0.0
      with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          head: release/${{ github.event.inputs.versionCode }}
          base: development
          title: ${{ github.event.inputs.versionCode }} into develop
          reviewers: ${{ github.event.issue.user.login }}
          body: |
              Hi!
              This PR was created in response workflow running.
              I've updated the version name and code commit: ${{ steps.make-commit.outputs.commit }}.